# Generated by Django 4.0.6 on 2023-06-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_of_registration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('title_blogpost', models.CharField(max_length=120)),
                ('text_blogpost', models.TextField(blank=True, null=True)),
                ('date_of_public_blogpost', models.DateTimeField(blank=True, null=True)),
                ('author_blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost', to='bloggin.author')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_topic', models.CharField(max_length=128)),
                ('text_topic', models.TextField(blank=True, null=True)),
                ('date_of_public_topic', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='bloggin.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(blank=True, null=True)),
                ('date_of_public_comment', models.DateTimeField(blank=True, null=True)),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='bloggin.author')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost', to='bloggin.blogpost')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topics',
            field=models.ManyToManyField(to='bloggin.topic'),
        ),
    ]
