# Generated by Django 4.0.6 on 2023-06-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggin', '0002_alter_blogpost_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
    ]
