# Generated by Django 4.0.6 on 2023-07-15 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloggin', '0007_remove_author_followers_topic_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='authors',
        ),
        migrations.AddField(
            model_name='topic',
            name='authors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
